# See the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "adidahiya"
    versioning-strategy: increase

  - package-ecosystem: "npm"
    directory: "/packages/colors"
    schedule:
      interval: "weekly"
    reviewers:
      - "adidahiya"
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: "@blueprintjs/*"

  - package-ecosystem: "npm"
    directory: "/packages/core"
    schedule:
      interval: "weekly"
    reviewers:
      - "adidahiya"
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: "@blueprintjs/*"

  - package-ecosystem: "npm"
    directory: "/packages/datetime"
    schedule:
      interval: "weekly"
    reviewers:
      - "adidahiya"
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: "@blueprintjs/*"

  - package-ecosystem: "npm"
    directory: "/packages/datetime2"
    schedule:
      interval: "weekly"
    reviewers:
      - "adidahiya"
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: "@blueprintjs/*"

  - package-ecosystem: "npm"
    directory: "/packages/demo-app"
    schedule:
      interval: "weekly"
    reviewers:
      - "adidahiya"
    versioning-strategy: increase
    ignore:
      - dependency-name: "@blueprintjs/*"

  - package-ecosystem: "npm"
    directory: "/packages/docs-app"
    schedule:
      interval: "weekly"
    reviewers:
      - "adidahiya"
    versioning-strategy: increase
    ignore:
      - dependency-name: "@blueprintjs/*"

  - package-ecosystem: "npm"
    directory: "/packages/docs-data"
    schedule:
      interval: "weekly"
    reviewers:
      - "adidahiya"
    versioning-strategy: increase
    ignore:
      - dependency-name: "@blueprintjs/*"

  - package-ecosystem: "npm"
    directory: "/docs-theme"
    schedule:
      interval: "weekly"
    reviewers:
      - "adidahiya"
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: "@blueprintjs/*"

  - package-ecosystem: "npm"
    directory: "/packages/eslint-config"
    schedule:
      interval: "weekly"
    reviewers:
      - "adidahiya"
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: "@blueprintjs/*"

  - package-ecosystem: "npm"
    directory: "/eslint-plugin"
    schedule:
      interval: "weekly"
    reviewers:
      - "adidahiya"
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: "@blueprintjs/*"

  - package-ecosystem: "npm"
    directory: "/packages/icons"
    schedule:
      interval: "weekly"
    reviewers:
      - "adidahiya"
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: "@blueprintjs/*"

  - package-ecosystem: "npm"
    directory: "/packages/karma-build-scripts"
    schedule:
      interval: "weekly"
    reviewers:
      - "adidahiya"
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: "@blueprintjs/*"

  - package-ecosystem: "npm"
    directory: "/packages/landing-app"
    schedule:
      interval: "weekly"
    reviewers:
      - "adidahiya"
    versioning-strategy: increase
    ignore:
      - dependency-name: "@blueprintjs/*"

  - package-ecosystem: "npm"
    directory: "/packages/node-build-scripts"
    schedule:
      interval: "weekly"
    reviewers:
      - "adidahiya"
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: "@blueprintjs/*"

  - package-ecosystem: "npm"
    directory: "/packages/popover2"
    schedule:
      interval: "weekly"
    reviewers:
      - "adidahiya"
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: "@blueprintjs/*"

  - package-ecosystem: "npm"
    directory: "/packages/select"
    schedule:
      interval: "weekly"
    reviewers:
      - "adidahiya"
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: "@blueprintjs/*"

  - package-ecosystem: "npm"
    directory: "/packages/stylelint-plugin"
    schedule:
      interval: "weekly"
    reviewers:
      - "adidahiya"
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: "@blueprintjs/*"

  - package-ecosystem: "npm"
    directory: "/packages/table"
    schedule:
      interval: "weekly"
    reviewers:
      - "adidahiya"
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: "@blueprintjs/*"

  - package-ecosystem: "npm"
    directory: "/packages/table-dev-app"
    schedule:
      interval: "weekly"
    reviewers:
      - "adidahiya"
    versioning-strategy: increase
    ignore:
      - dependency-name: "@blueprintjs/*"

  - package-ecosystem: "npm"
    directory: "/packages/test-commons"
    schedule:
      interval: "weekly"
    reviewers:
      - "adidahiya"
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: "@blueprintjs/*"

  - package-ecosystem: "npm"
    directory: "/packages/timezone"
    schedule:
      interval: "weekly"
    reviewers:
      - "adidahiya"
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: "@blueprintjs/*"

  - package-ecosystem: "npm"
    directory: "/packages/webpack-build-scripts"
    schedule:
      interval: "weekly"
    reviewers:
      - "adidahiya"
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: "@blueprintjs/*"
